// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCue3VlLC4XzMrbtXUNitEgiS-JQYmfGTs',
    appId: '1:1012039873572:web:67a6b27dc14a19b55294b1',
    messagingSenderId: '1012039873572',
    projectId: 'places-88363',
    authDomain: 'places-88363.firebaseapp.com',
    storageBucket: 'places-88363.firebasestorage.app',
    measurementId: 'G-C34P8TZ1TF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBumSTiZINvc6NtaSHmU2FlP2IKdtGYmuE',
    appId: '1:1012039873572:android:7483e5e4c66482a05294b1',
    messagingSenderId: '1012039873572',
    projectId: 'places-88363',
    storageBucket: 'places-88363.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBPfrtKoBhuCuApNINg-TcBNovQ1rXtHM',
    appId: '1:1012039873572:ios:564b8977c48567b05294b1',
    messagingSenderId: '1012039873572',
    projectId: 'places-88363',
    storageBucket: 'places-88363.firebasestorage.app',
    iosBundleId: 'com.example.places2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBPfrtKoBhuCuApNINg-TcBNovQ1rXtHM',
    appId: '1:1012039873572:ios:564b8977c48567b05294b1',
    messagingSenderId: '1012039873572',
    projectId: 'places-88363',
    storageBucket: 'places-88363.firebasestorage.app',
    iosBundleId: 'com.example.places2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCue3VlLC4XzMrbtXUNitEgiS-JQYmfGTs',
    appId: '1:1012039873572:web:fe3d28ef766e8c355294b1',
    messagingSenderId: '1012039873572',
    projectId: 'places-88363',
    authDomain: 'places-88363.firebaseapp.com',
    storageBucket: 'places-88363.firebasestorage.app',
    measurementId: 'G-VQ9PVZN4M8',
  );
}
